-- MySQL Script generated by MySQL Workbench
-- Thu Nov 19 16:09:40 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema certificates
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `certificates` ;

-- -----------------------------------------------------
-- Schema certificates
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `certificates` DEFAULT CHARACTER SET utf8 ;
USE `certificates` ;

-- -----------------------------------------------------
-- Table `certificates`.`gift_certificate`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `certificates`.`gift_certificate` ;

CREATE TABLE IF NOT EXISTS `certificates`.`gift_certificate` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` TEXT NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  `create_date` TIMESTAMP NOT NULL,
  `last_update_date` TIMESTAMP NOT NULL,
  `duration` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `int_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `certificates`.`tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `certificates`.`tag` ;

CREATE TABLE IF NOT EXISTS `certificates`.`tag` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `certificates`.`gift_certificate2tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `certificates`.`gift_certificate2tag` ;

CREATE TABLE IF NOT EXISTS `certificates`.`gift_certificate2tag` (
  `gift_certificate_id` INT NOT NULL,
  `tag_id` INT NOT NULL,
  INDEX `gift_certificate_fk_idx` (`gift_certificate_id` ASC) VISIBLE,
  INDEX `tag_id_fk_idx` (`tag_id` ASC) VISIBLE,
  CONSTRAINT `gift_certificate_id_fk`
    FOREIGN KEY (`gift_certificate_id`)
    REFERENCES `certificates`.`gift_certificate` (`id`),
  CONSTRAINT `tag_id_fk`
    FOREIGN KEY (`tag_id`)
    REFERENCES `certificates`.`tag` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `certificates`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `certificates`.`user` ;

CREATE TABLE IF NOT EXISTS `certificates`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `certificates`.`order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `certificates`.orders ;

CREATE TABLE IF NOT EXISTS `certificates`.`order` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `gift_certificate_id` INT NOT NULL,
  `cost` DECIMAL(10,2) NOT NULL,
  `purchase_date` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_fk_idx` (`user_id` ASC) VISIBLE,
  INDEX `gift_certificate_fk_idx` (`gift_certificate_id` ASC) VISIBLE,
  CONSTRAINT `user_fk`
    FOREIGN KEY (`user_id`)
    REFERENCES `certificates`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `gift_certificate_fk`
    FOREIGN KEY (`gift_certificate_id`)
    REFERENCES `certificates`.`gift_certificate` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
